<a href="https://colab.research.google.com/github/JAYMAN735/ML-Projects/blob/main/DPDM_Class_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import sqlite3

### Loading `website_sales.db` (SQLite Database)

First, I will connect to the SQLite database and list the tables to identify the relevant sales table. Then, I will load the data from that table into a DataFrame.

In [15]:
conn = sqlite3.connect('/content/website_sales.db')
cursor = conn.cursor()

# Get table names from the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in website_sales.db:", tables)

# Assuming 'sales' is the table name, load it into a DataFrame
# You might need to adjust 'sales' if the table name is different
website_sales_df = pd.read_sql_query("SELECT * FROM sales", conn)
conn.close()

display(website_sales_df.head())

Tables in website_sales.db: [('sales',)]

         date     product  units  revenue
0  2026-03-01      Laptop     24    40752
1  2026-03-01       Phone     59   514067
2  2026-03-01  Headphones     29    78445
3  2026-03-01    Keyboard     22   382426
4  2026-03-01       Mouse     75  1483950

### Loading `amazon_sales.csv`

Next, I will load the `amazon_sales.csv` file into a pandas DataFrame.

In [16]:
amazon_sales_df = pd.read_csv('/content/amazon_sales.csv')
display(amazon_sales_df.head())

         date     product  units_sold  price
0  01-03-2026      Laptop          95  48594
1  01-03-2026       Phone          17  19754
2  01-03-2026  Headphones          69  32264
3  01-03-2026    Keyboard          13  30108
4  01-03-2026       Mouse          98  38809

### Loading `flipkart_sales.json`

Finally, I will load the `flipkart_sales.json` file into a pandas DataFrame.

In [17]:
flipkart_sales_df = pd.read_json('/content/flipkart_sales.json')
display(flipkart_sales_df.head())

        date product_name  quantity  unit_price
0 2026-03-01       Laptop        26       32045
1 2026-03-01        Phone        23        5674
2 2026-03-01   Headphones        52       27519
3 2026-03-01     Keyboard        13       31494
4 2026-03-01        Mouse        54       12000

In [18]:
# Convert the 'date' column in amazon_sales_df to datetime objects first
amazon_sales_df['date'] = pd.to_datetime(amazon_sales_df['date'], format='%d-%m-%Y')

# Now, format the datetime objects to 'YYYY-MM-DD' string format
amazon_sales_df['date'] = amazon_sales_df['date'].dt.strftime('%Y-%m-%d')

print("Date format in amazon_sales_df updated to 'YYYY-MM-DD':")
display(amazon_sales_df.head())

Date format in amazon_sales_df updated to 'YYYY-MM-DD':

         date     product  units_sold  price
0  2026-03-01      Laptop          95  48594
1  2026-03-01       Phone          17  19754
2  2026-03-01  Headphones          69  32264
3  2026-03-01    Keyboard          13  30108
4  2026-03-01       Mouse          98  38809

In [19]:
amazon_sales_df = amazon_sales_df.rename(columns={'units_sold': 'units'})
print("Column 'units_sold' renamed to 'units' in amazon_sales_df:")
display(amazon_sales_df.head())

Column 'units_sold' renamed to 'units' in amazon_sales_df:

         date     product  units  price
0  2026-03-01      Laptop     95  48594
1  2026-03-01       Phone     17  19754
2  2026-03-01  Headphones     69  32264
3  2026-03-01    Keyboard     13  30108
4  2026-03-01       Mouse     98  38809

In [20]:
flipkart_sales_df = flipkart_sales_df.rename(columns={'product_name': 'product', 'quantity': 'units', 'unit_price': 'price'})
print("Columns renamed in flipkart_sales_df:")
display(flipkart_sales_df.head())

Columns renamed in flipkart_sales_df:

        date     product  units  price
0 2026-03-01      Laptop     26  32045
1 2026-03-01       Phone     23   5674
2 2026-03-01  Headphones     52  27519
3 2026-03-01    Keyboard     13  31494
4 2026-03-01       Mouse     54  12000

In [21]:
print("--- Info for website_sales_df ---")
print(website_sales_df.info())
display(website_sales_df.head())

--- Info for website_sales_df ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     object
 1   product  50 non-null     object
 2   units    50 non-null     int64
 3   revenue  50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
None

         date     product  units  revenue
0  2026-03-01      Laptop     24    40752
1  2026-03-01       Phone     59   514067
2  2026-03-01  Headphones     29    78445
3  2026-03-01    Keyboard     22   382426
4  2026-03-01       Mouse     75  1483950

### `amazon_sales_df` (Amazon Sales)
This DataFrame contains sales data from Amazon. The 'date' column has been formatted to 'YYYY-MM-DD' and 'units_sold' has been renamed to 'units'.

In [22]:
print("\n--- Info for amazon_sales_df ---")
print(amazon_sales_df.info())
display(amazon_sales_df.head())

--- Info for amazon_sales_df ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     object
 1   product  50 non-null     object
 2   units    50 non-null     int64
 3   price    50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
None

         date     product  units  price
0  2026-03-01      Laptop     95  48594
1  2026-03-01       Phone     17  19754
2  2026-03-01  Headphones     69  32264
3  2026-03-01    Keyboard     13  30108
4  2026-03-01       Mouse     98  38809

### `flipkart_sales_df` (Flipkart Sales)
This DataFrame contains sales data from Flipkart. The columns 'product_name', 'quantity', and 'unit_price' have been renamed to 'product', 'units', and 'price' respectively.

In [23]:
print("\n--- Info for flipkart_sales_df ---")
print(flipkart_sales_df.info())
display(flipkart_sales_df.head())

--- Info for flipkart_sales_df ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     datetime64[ns]
 1   product  50 non-null     object
 2   units    50 non-null     int64
 3   price    50 non-null     int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 1.7+ KB
None

        date     product  units  price
0 2026-03-01      Laptop     26  32045
1 2026-03-01       Phone     23   5674
2 2026-03-01  Headphones     52  27519
3 2026-03-01    Keyboard     13  31494
4 2026-03-01       Mouse     54  12000

In [24]:
flipkart_sales_df['date'] = flipkart_sales_df['date'].dt.strftime('%Y-%m-%d')
print("Date format in flipkart_sales_df updated to 'YYYY-MM-DD' and type converted to object:")
display(flipkart_sales_df.head())

Date format in flipkart_sales_df updated to 'YYYY-MM-DD' and type converted to object:

         date     product  units  price
0  2026-03-01      Laptop     26  32045
1  2026-03-01       Phone     23   5674
2  2026-03-01  Headphones     52  27519
3  2026-03-01    Keyboard     13  31494
4  2026-03-01       Mouse     54  12000

In [25]:
print(flipkart_sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     object
 1   product  50 non-null     object
 2   units    50 non-null     int64
 3   price    50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
None

In [26]:
# Add a 'source' column to each DataFrame
amazon_sales_df['source'] = 'amazon'
flipkart_sales_df['source'] = 'flipkart'

# Merge the two DataFrames using concat
combined_sales_df = pd.concat([amazon_sales_df, flipkart_sales_df], ignore_index=True)

print("Combined DataFrame head:")
display(combined_sales_df.head())

print("\nCombined DataFrame info:")
print(combined_sales_df.info())

Combined DataFrame head:

         date     product  units  price  source
0  2026-03-01      Laptop     95  48594  amazon
1  2026-03-01       Phone     17  19754  amazon
2  2026-03-01  Headphones     69  32264  amazon
3  2026-03-01    Keyboard     13  30108  amazon
4  2026-03-01       Mouse     98  38809  amazon

Combined DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     100 non-null    object
 1   product  100 non-null    object
 2   units    100 non-null    int64
 3   price    100 non-null    int64
 4   source   100 non-null    object
dtypes: int64(2), object(3)
memory usage: 4.0+ KB
None

In [27]:
combined_sales_df['revenue'] = combined_sales_df['units'] * combined_sales_df['price']
print("Combined DataFrame with 'revenue' column:")
display(combined_sales_df.head())

Combined DataFrame with 'revenue' column:

         date     product  units  price  source  revenue
0  2026-03-01      Laptop     95  48594  amazon  4616430
1  2026-03-01       Phone     17  19754  amazon   335818
2  2026-03-01  Headphones     69  32264  amazon  2226216
3  2026-03-01    Keyboard     13  30108  amazon   391404
4  2026-03-01       Mouse     98  38809  amazon  3803282

In [28]:
website_sales_df['source'] = 'website'
print("website_sales_df with 'source' column:")
display(website_sales_df.head())

website_sales_df with 'source' column:

         date     product  units  revenue   source
0  2026-03-01      Laptop     24    40752  website
1  2026-03-01       Phone     59   514067  website
2  2026-03-01  Headphones     29    78445  website
3  2026-03-01    Keyboard     22   382426  website
4  2026-03-01       Mouse     75  1483950  website

In [29]:
website_sales_df['price'] = website_sales_df['revenue'] / website_sales_df['units']
print("website_sales_df with new 'price' column:")
display(website_sales_df.head())

website_sales_df with new 'price' column:

         date     product  units  revenue   source    price
0  2026-03-01      Laptop     24    40752  website   1698.0
1  2026-03-01       Phone     59   514067  website   8713.0
2  2026-03-01  Headphones     29    78445  website   2705.0
3  2026-03-01    Keyboard     22   382426  website  17383.0
4  2026-03-01       Mouse     75  1483950  website  19786.0

In [30]:
final_combined_sales_df = pd.concat([combined_sales_df, website_sales_df], ignore_index=True)

print("Final Combined DataFrame head:")
display(final_combined_sales_df.head())

print("\nFinal Combined DataFrame info:")
print(final_combined_sales_df.info())

Final Combined DataFrame head:

         date     product  units    price  source  revenue
0  2026-03-01      Laptop     95  48594.0  amazon  4616430
1  2026-03-01       Phone     17  19754.0  amazon   335818
2  2026-03-01  Headphones     69  32264.0  amazon  2226216
3  2026-03-01    Keyboard     13  30108.0  amazon   391404
4  2026-03-01       Mouse     98  38809.0  amazon  3803282

Final Combined DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     150 non-null    object
 1   product  150 non-null    object
 2   units    150 non-null    int64
 3   price    150 non-null    float64
 4   source   150 non-null    object
 5   revenue  150 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 7.2+ KB
None